version: 1.0.{build}
image: Ubuntu

environment:
  DOCKER_USER:
    secure: 04T1JyfyhfcvC1+4KIJg4A==
  DOCKER_PASS:
    secure: T5atRDJZWwSIN1388pnTqw==


install:
  - docker version

build_script:
  - docker build -t deploy/app:1.0.{build} .

# test_script:
#   - docker run me/myfavoriteapp

deploy_script:
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker push peresadaoleg/olegperesada:1.0.{build}