version: 1.0.{build}
image: Ubuntu1804

environment:
  DOCKER_USER:
    secure: 04T1JyfyhfcvC1+4KIJg4A==
  DOCKER_PASS:
    secure: T5atRDJZWwSIN1388pnTqw==

install:
  - docker version
  - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && 
  chmod +x /usr/local/bin/docker-compose && 
  ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose &&
  docker-compose --version

build_script:
  - docker build -t deploy/app:coreapp .

# test_script:
#   - docker run me/myfavoriteapp

deploy_script:
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker tag deploy/app:coreapp peresadaoleg/olegperesada:coreapp
  - docker push peresadaoleg/olegperesada:coreapp