version: 1.0.{build}
image: Ubuntu1804

environment:
  DOCKER_USER:
    secure: 04T1JyfyhfcvC1+4KIJg4A==
  DOCKER_PASS:
    secure: T5atRDJZWwSIN1388pnTqw==

install:
  - docker version
  - cinst docker-compose

build_script:
  - docker build -t deploy/app:coreapp .

# test_script:
#   - docker run me/myfavoriteapp

deploy_script:
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker tag deploy/app:coreapp peresadaoleg/olegperesada:coreapp
  - docker push peresadaoleg/olegperesada:coreapp